version: "3.9"

services:
  app:
    image: nodejs-tsc
    restart: unless-stopped
    ports:
      - "3000:8080"
    networks:
        vpcbr:
          ipv4_address: 172.5.0.6
  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=citizix
      - MONGO_INITDB_ROOT_PASSWORD=S3cret  
volumes:
  cache:
    driver: local

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 172.5.0.0/16
         gateway: 172.5.0.1